spring:
  application:
    name: employee-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:EMPLOYEEDEB
    username: sa
    password:
    h2:
      console:
        enabled: true
        path: /h2
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true
      hibernate:
        ddl-auto: update
  zipkin:
    base-url: http://localhost:9411/zipkin/
  sleuth:
    sampler:
      percentage: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  healthcheck:
    enabled: true
  instance:
    hostname: localhost
    #prefer-ip-address: true

server:
  port: 8890

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /userInfo
      exposure:
        include: "*"
logging:
  level:
    root: INFO

