spring:
  application:
    name: orders-details
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:order_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    h2:
      console:
        enabled: true
        path: /h2
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true
      hibernate:
        ddl-auto: none

    zipkin:
      base-url: http://localhost:9411
      enabled: false
    sleuth:
      enabled: true
ribbon:
  ReadTimeout: 2000000
  ConnectTimeout: 2000000
  IsSecure: false
server:
  port:
    8754
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true